name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install Client Dependencies
        run: npm ci --no-audit --no-fund --omit=optional
      - name: Lint Client
        run: npx eslint

  deploy-client:
      needs: lint
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Deploy Client to Heroku
          uses: akhileshns/heroku-deploy@v3.12.13
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_API_APP }}
            heroku_email: ${{ secrets.HEROKU_API_EMAIL }}
            buildpack: heroku/nodejs